title:
  home: Home
  archive: Archives
  category: Categories
  album: Albums

menu:
  home: Home
  archives: Archives
  albums: Albums

archives:
  title: Archives
  tags: Tags
  categories: Categories
  time: Time
  none: None

format:
  post: 'YYYY-MM-DD'
  post_list: "YYYY-MM-DD"
  archive_list: "YYYY-MM"
  archive_month: "YYYY-MM"

pagination:
  prev: Prev
  next: Next

toc_title: Table Of Content