
# html lang
language:
- en
- zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  albums: /albums

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- //cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.css
- /css/vs2015.css
- /css/fabric.css

# scripts loaded in the end of the body
scripts:
- //cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.js
- /js/highlight.pack.js
- /js/fabric.js

my_qiniu_image_base: http://oxpdn0tpt.bkt.clouddn.com
my_qiniu_image_style: imageView2/0/interlace/1/q/75|imageslim

node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
  indentedSyntax: true
  includePaths:
    - ./themes/fabric/node_modules/bourbon/core