
# html lang
language: en

# main menu navigation
menu:
  Home: /
  # About: /about
  # Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/typo.css
- /css/fabric.css
- /css/prettify.css
- /css/prettify/sunburst.css

# scripts loaded in the end of the body
scripts:
- /js/prettify/prettify.js
- /js/prettify/lang-css.js
- /js/fabric.js

node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
  indentedSyntax: true
